---
title: "Dagloan dendro"
author: "G. Moroz"
date: '3 февраля 2018 г'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Возьмем-ка единички и нолики созданные Самирой, построим кластеризацию и раскрасим по переменной `cognate_set`

```{r, fig.height= 7, fig.width= 7}
library(magrittr)
library(ape)

df <- read.csv("data.csv", stringsAsFactors = FALSE)

data <- df[,-c(1:3)]
row.names(data) <- paste(1:294, df$english)

data %>% 
  dist() %>% 
  hclust(method = "ward.D2") ->
  hc

plot(as.phylo(hc), 
     type = "fan",
     cex = 0.6,
     no.margin = TRUE,
     tip.color = c("red",
                   "blue",
                   "green",
                   "black",
                   "yellow",
                   "pink", 
                   "navy")[as.factor(df$cognate_set)])
```

Если внимательно смотреть на границу круга, то можно увидеть, что часто в один кластер попадают слова из одинакового `cognate_set`.

Еще можно аналогично кластеризовать языки, но, подозреваю, лингвистической информации здесь мало.
